# Generated by Django 4.2 on 2024-11-28 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='Unknown', max_length=50)),
                ('prenom', models.CharField(default='Unknown', max_length=50)),
                ('telephone', models.CharField(default='Unknown', max_length=15)),
                ('mot_de_passe', models.CharField(default='Unknown', max_length=10000)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('salt', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('failed_at', models.CharField(default='no', null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.utilisateur')),
            ],
        ),
    ]
